[fs-uae]
amiga_model = A500
cpu = 68000
accuracy = 1
floppy_drive_0 = @AXIOMICA_ADF@
floppy_drive_speed = 100
fullscreen = 0
window_width = 752
window_height = 574
console_debugger = 1
keyboard_key_f10 = action_debugger
